### ISSUE TITLE
doesn't seem to work with computed properties in traits

### ISSUE THREAD

**Issue by aoxborrow** [calebdw/larastan-livewire#3]
thanks for this, silenced a bunch of them. but I have a computed property `paginator` in trait `withPagination`, and phpstan says no

![ScreenShot 2024-09-06 at 14 10 51](https://github.com/user-attachments/assets/177a8acd-1967-4232-bfed-533cd6c1ae57)

**Comment by calebdw** [comment]
Can you please show the trait?

**Comment by calebdw** [comment]
I added a test for computed properties on traits and they passed: 6e6a556048511d3dd1b559eb0477e1298dde2c62

Please make sure the methods are defined appropriately

**Comment by aoxborrow** [comment]
hmm maybe because my base class is abstract:

```php
abstract class TableComponent extends Component
{
    use WithPagination;
    ...

trait WithPagination
{
    #[Computed]
    public function paginator() {
        ...
    }

**Comment by aoxborrow** [comment]
changing to concrete class clears the phpstan errors, although I'm not sure it should be an issue

**Comment by calebdw** [comment]
Where are you calling the property at?

**Comment by aoxborrow** [comment]
only within the trait that defines it

**Comment by aoxborrow** [comment]
quick work -- thank you!
